### ISSUE TITLE
minimum python for tiktok-bot is python 3.6 + utf8 encoding issue

### ISSUE THREAD

**Issue by ya3ya6** [elliotalderson-py/tiktoktool#1]
Hi.
It's a cool project.
i just ran onto some issues:
1. i had python 3.5, and i get error when tried to install "tiktok-bot". i searched for solution at it turned out it only support 3.6+. i upgraded to 3.8 and it worked.
2. i get error when running it. this error: `'charmap' codec can't encode character '\U0001f602'`
searched for it, fount this: https://stackoverflow.com/a/54599306/4718434
so i changed 3 fopen codes in "TikTokTool.py" (added the utf-8), and it worked.

Thanks again for the tool.

**Comment by elliotalderson-py** [comment]
I have never run into these problems, but I added your solutions and I update the readme file for the other users. Thanks a lot!
